# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Angular.js-server
email: antoine.lucas.australia@gmail.com
description: Angular.js-server is a libary running on node.js that brings the power of server side rendering to AngularJS Web apps.
keywords: Angular.js, Server side rendering, Node.js, Modern Javascript, Server side rendering with Angular.js
author: Antoine LUCAS ( https://www.github.com/a-lucas )
baseurl_prod: "https://a-lucas.github.io/angular.js-server/" # the subpath of your site, e.g. /blog
baseurl_dev: "/"
url: "https://a-lucas.github.io/" # the base hostname & protocol for your site
github_username:  a-lucas
repository: a-lucas/angular.js-server
# Build settings
markdown: kramdown